/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BLL.BillBLL;
import BLL.BillInfoBLL;
import BLL.TableBLL;
import DAO.BillDAO;
import javax.swing.JOptionPane;


/**
 *
 * @author lizid
 */
public class QuantityGUI extends javax.swing.JFrame {

    /**
     * Creates new form QuantityGUI
     */
    
    int tableId, foodId;
    String tableName;
    protected BillInfoBLL billInfoBLL;
    protected TableBLL tableBLL;
    public QuantityGUI(int tableId_p,String tableName_p, int foodId_p) {
        initComponents();
        tableId=tableId_p;
        tableName=tableName_p;
        foodId=foodId_p;
    }

    private QuantityGUI() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spQuantity = new javax.swing.JSpinner();
        btnChooseQuantity = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtQuantityNote = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chọn số lượng cho món ăn");

        spQuantity.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        btnChooseQuantity.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnChooseQuantity.setText("Thêm món");
        btnChooseQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseQuantityActionPerformed(evt);
            }
        });

        txtQuantityNote.setColumns(20);
        txtQuantityNote.setRows(5);
        jScrollPane1.setViewportView(txtQuantityNote);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Chú thích :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(spQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnChooseQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnChooseQuantity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spQuantity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnChooseQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseQuantityActionPerformed

        BillBLL billBLL = new BillBLL();
        
        int quantity=(int) spQuantity.getValue();
        
        if(quantity <1){
            JOptionPane.showMessageDialog(this, "Số lượng không thể nhỏ hơn 0!");
        }
        else{
            String note=txtQuantityNote.getText();
            billBLL.AddOrUpdateBill(tableId, foodId, quantity, note);
        
            this.setVisible(false);;
            billInfoBLL = new BillInfoBLL();
            BillDAO billDAO =new BillDAO();
            int billId=billDAO.GetBillId(tableId);
            billInfoBLL.FillBillItem(TableGUI.jTable1,billId);
            
            MainGUI.flpTable.removeAll();
            tableBLL =new TableBLL();
            tableBLL.loadTable(MainGUI.flpTable);
            MainGUI.flpTable.validate();
            MainGUI.flpTable.revalidate();
            MainGUI.flpTable.repaint();
        }
        
      
    }//GEN-LAST:event_btnChooseQuantityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuantityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuantityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuantityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuantityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuantityGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChooseQuantity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JSpinner spQuantity;
    public static javax.swing.JTextArea txtQuantityNote;
    // End of variables declaration//GEN-END:variables
}
