/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BillBLL;
import BLL.BillInfoBLL;
import BLL.FoodBLL;
import BLL.TableBLL;
import DAO.BillDAO;
import DTO.FoodDTO;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *
 * @author lizid
 */
public class TableGUI extends javax.swing.JFrame {

    /**
     * Creates new form TableGUI
     */
    protected BillInfoBLL billInfoBLL;
    protected BillBLL billBLL;
    protected FoodBLL foodBLL;
    protected TableBLL tableBLL;
    protected BillDAO billDAO;
    private final String tableName;
    private final int tableId;
    public TableGUI(String tableName_p,int tableId_p) {
        
       
        initComponents();
        tableName=tableName_p;
        tableId=tableId_p;
        billDAO = new BillDAO();
        int billId = billDAO.GetBillId(tableId);
        billInfoBLL= new BillInfoBLL();
        billInfoBLL.FillBillItem(jTable1, billId);
        LoadMenu();
        LoadChageTableCbBox();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTableName = new javax.swing.JLabel();
        flpTableBill = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbCheckIn = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnPay = new javax.swing.JButton();
        btnDatBan = new javax.swing.JButton();
        btnHuyDatBan = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnDiscount = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        spDiscount = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        btnChangeTable = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cbChangeTable = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(1366, 768));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        lbTableName.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbTableName.setText("Tên bàn");

        flpTableBill.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Thời gian vào:");

        lbCheckIn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbCheckIn.setText("00:00:00");

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bill Info Id", "Tên món", "Chú thích", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(1);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        btnPay.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnPay.setText("Thanh toán");
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        btnDatBan.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnDatBan.setText("Đặt bàn");
        btnDatBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatBanActionPerformed(evt);
            }
        });

        btnHuyDatBan.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btnHuyDatBan.setText("Hủy đặt bàn");
        btnHuyDatBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyDatBanActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnDiscount.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnDiscount.setText("Giảm giá");
        btnDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiscountActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Giảm giá( %):");

        spDiscount.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(spDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnChangeTable.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnChangeTable.setText("Chuyển bàn");
        btnChangeTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeTableActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Bàn cần chuyển:");

        cbChangeTable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnChangeTable, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cbChangeTable, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cbChangeTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnChangeTable, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Tổng: ");

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtTotal.setHorizontalAlignment(SwingConstants.RIGHT);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("VNĐ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTableName, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addComponent(flpTableBill, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbCheckIn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnDatBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHuyDatBan, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(btnPay, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addGap(21, 21, 21)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTableName, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(lbCheckIn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtTotal)
                                .addComponent(jLabel4)))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnDatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(btnHuyDatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9))
                                    .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(41, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(flpTableBill, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDatBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatBanActionPerformed
        TableBLL tableBLL = new TableBLL();
        tableBLL.changeTableStatus(tableId, "Bàn đặt");
        JOptionPane.showMessageDialog(this, "Đã chuyển trạng thái thành đặt bàn thành công!");
        
        MainGUI.flpTable.removeAll();
            tableBLL =new TableBLL();
            tableBLL.loadTable(MainGUI.flpTable);
            MainGUI.flpTable.validate();
            MainGUI.flpTable.revalidate();
            MainGUI.flpTable.repaint();
    }//GEN-LAST:event_btnDatBanActionPerformed

    private void btnHuyDatBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyDatBanActionPerformed
        TableBLL tableBLL = new TableBLL();
        tableBLL.changeTableStatus(tableId, "Trống");
        JOptionPane.showMessageDialog(this, "Đã hủy trạng thái đặt bàn!");
        
        MainGUI.flpTable.removeAll();
            tableBLL =new TableBLL();
            tableBLL.loadTable(MainGUI.flpTable);
            MainGUI.flpTable.validate();
            MainGUI.flpTable.revalidate();
            MainGUI.flpTable.repaint();
    }//GEN-LAST:event_btnHuyDatBanActionPerformed

    private void btnDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiscountActionPerformed
        if((Integer)spDiscount.getValue()>100||(Integer)spDiscount.getValue()<0 ){
            JOptionPane.showMessageDialog(this, "Số lượng giảm giá không đúng!");
            billDAO = new BillDAO();
            int billId = billDAO.GetBillId(tableId);
            spDiscount.setValue(billDAO.GetDiscount(billId));
        }
        else{
            int discount = (int) spDiscount.getValue();
            billBLL=new BillBLL();
            billBLL.Discount(tableId, discount);
            billDAO = new BillDAO();
            int billId = billDAO.GetBillId(tableId);
            billInfoBLL= new BillInfoBLL();
            billInfoBLL.FillBillItem(jTable1, billId);
        }
    }//GEN-LAST:event_btnDiscountActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        String tableName = lbTableName.getText();
        String total = txtTotal.getText();
        int discount = (int) spDiscount.getValue();
        String message = "Bạn có muốn thanh toán "+tableName+" với giảm giá là "+discount+ "% và tổng Bill là: "+total+" VNĐ ?";
        JLabel label = new JLabel(message);
        label.setFont(new Font("Arial", Font.BOLD, 18));
        int result = JOptionPane.showConfirmDialog(this, label,"Thông báo",JOptionPane.OK_CANCEL_OPTION);
        if(result == JOptionPane.YES_OPTION){
            billBLL =new BillBLL();
            billBLL.CheckOutBill(tableId, discount);
            this.dispose();
            
            
            MainGUI.flpTable.removeAll();
            tableBLL =new TableBLL();
            tableBLL.loadTable(MainGUI.flpTable);
            MainGUI.flpTable.validate();
            MainGUI.flpTable.revalidate();
            MainGUI.flpTable.repaint();
        }
        
        
        

       
    }//GEN-LAST:event_btnPayActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        int billInfoId = 0;
        String note = "";
        int count = 0;
        int row = jTable1.getSelectedRow();
        if(row>=0){
            billInfoId=(int) jTable1.getValueAt(row, 0);
            note=jTable1.getValueAt(row, 2).toString();
            count = (int) jTable1.getValueAt(row, 3);
        }
        UpdateBillItemGUI updateGUI = new UpdateBillItemGUI(tableId);
        UpdateBillItemGUI.txtBillInfoId.setText(Integer.toString(billInfoId));
        UpdateBillItemGUI.sp_ItemQuantity.setValue(count);
        UpdateBillItemGUI.txt_UpdateNote.setText(note);
        updateGUI.setVisible(true);
//        this.setEnabled(false);
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnChangeTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeTableActionPerformed
        String newTable = (String) cbChangeTable.getSelectedItem();
        tableBLL = new TableBLL();
        tableBLL.ChangeTable(newTable, tableId);
        MainGUI.flpTable.removeAll();
            tableBLL =new TableBLL();
            tableBLL.loadTable(MainGUI.flpTable);
            MainGUI.flpTable.validate();
            MainGUI.flpTable.revalidate();
            MainGUI.flpTable.repaint();
    }//GEN-LAST:event_btnChangeTableActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TableGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TableGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TableGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TableGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TableGUI(tableName_p,tableId_p)).setVisible(true);
//            }
//        });
//    }
    
    public void LoadChageTableCbBox(){
        tableBLL = new TableBLL();
        ArrayList<String> listTableName = new ArrayList<String>();
        listTableName=tableBLL.GetListTableNameNonBill();
        for(int i=0; i<listTableName.size();i++){
            cbChangeTable.addItem(listTableName.get(i));

        }
    }
    public void LoadMenu(){
        billDAO = new BillDAO();
        SimpleDateFormat datefm =new SimpleDateFormat("HH:mm:ss");
        lbCheckIn.setText(billDAO.getCheckIn(billDAO.GetBillId(tableId)));
        lbTableName.setText(tableName);
        foodBLL =new FoodBLL();
        ArrayList<FoodDTO> listFood= foodBLL.getListFood();
        for(int i=0;i<listFood.size();i++){
            int catId=listFood.get(i).getCatId();
            int foodId=listFood.get(i).getFoodId();
            String foodName= listFood.get(i).getFoodName();
            String foodPrice =listFood.get(i).getFoodPrice();
            JButton button = new JButton("<html>" + foodName + "<br>" + foodPrice + "</html>");
            button.setPreferredSize(new Dimension(100, 100));
            button.setFont(new Font("Arial", Font.BOLD, 14));
            flpTableBill.add(button);
            switch(catId%10){
                case 1:
                    button.setBackground(Color.CYAN);
                    break;
                case 2:
                    button.setBackground(Color.YELLOW);
                    break;
                case 3:
                    button.setBackground(Color.GRAY);
                    break;
                case 4:
                    button.setBackground(Color.white);
                    break;
                case 5:
                    button.setBackground(Color.LIGHT_GRAY);
                    break;
                case 6:
                    button.setBackground(Color.GREEN);
                    break;
                case 7:
                    button.setBackground(Color.BLUE);
                    break;
                case 8:
                    button.setBackground(Color.MAGENTA);
                    break;
                case 9:
                    button.setBackground(Color.RED);
                    break;
                case 10:
                    button.setBackground(Color.lightGray);
                    break;
                default:
                    button.setBackground(Color.ORANGE);
                    break;
                
            }
            button.addActionListener(new ActionListener(){
                @Override
                public void actionPerformed(ActionEvent e){
                    QuantityGUI qGUI=new QuantityGUI(tableId,tableName,foodId);
                    qGUI.setVisible(true);
                    
                }


            });
        }
        if(lbCheckIn.getText()=="00:00:00"){
                btnDatBan.setVisible(true);
                btnHuyDatBan.setVisible(true);
        }else{
            
                btnDatBan.setVisible(false);
                btnHuyDatBan.setVisible(false);
        }
                
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangeTable;
    private javax.swing.JButton btnDatBan;
    private javax.swing.JButton btnDiscount;
    private javax.swing.JButton btnHuyDatBan;
    private javax.swing.JButton btnPay;
    private javax.swing.JComboBox<String> cbChangeTable;
    private javax.swing.JPanel flpTableBill;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    public static javax.swing.JLabel lbCheckIn;
    private javax.swing.JLabel lbTableName;
    public static javax.swing.JSpinner spDiscount;
    public static javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
