/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BLL.BillInfoBLL;
import DAO.BillDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author lizid
 */
public class UpdateBillItemGUI extends javax.swing.JFrame {

    /**
     * Creates new form UpdateBillItemGUI
     */
    protected BillInfoBLL billInfoBLL;
    private int tableId;
    public UpdateBillItemGUI(int tableId_p) {
        tableId=tableId_p;
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sp_ItemQuantity = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        btn_UpdateBillItem = new javax.swing.JButton();
        btn_DeleteBillItem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtBillInfoId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_UpdateNote = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        sp_ItemQuantity.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Chú thích: ");

        btn_UpdateBillItem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_UpdateBillItem.setText("Cập nhật");
        btn_UpdateBillItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateBillItemActionPerformed(evt);
            }
        });

        btn_DeleteBillItem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_DeleteBillItem.setText("Xóa món");
        btn_DeleteBillItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteBillItemActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Cập nhật/ Xóa món ăn");

        txtBillInfoId.setEditable(false);

        txt_UpdateNote.setColumns(20);
        txt_UpdateNote.setRows(5);
        jScrollPane1.setViewportView(txt_UpdateNote);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sp_ItemQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(btn_DeleteBillItem, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_UpdateBillItem, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBillInfoId, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel2)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBillInfoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sp_ItemQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_DeleteBillItem, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_UpdateBillItem, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_UpdateBillItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateBillItemActionPerformed
        int billInfoId=Integer.parseInt(txtBillInfoId.getText());
        int quantity=(int) sp_ItemQuantity.getValue();
        String note=txt_UpdateNote.getText();
        
        billInfoBLL = new BillInfoBLL();
        billInfoBLL.UpdateBillItem(billInfoId, quantity, note);
        
        JOptionPane.showMessageDialog(this, "Cập nhật món ăn thành công!");
        this.dispose();
        BillDAO billDAO =new BillDAO();
        int billId=billDAO.GetBillId(tableId);
        billInfoBLL.FillBillItem(TableGUI.jTable1,billId);
    }//GEN-LAST:event_btn_UpdateBillItemActionPerformed

    private void btn_DeleteBillItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteBillItemActionPerformed
        int billInfoId=Integer.parseInt(txtBillInfoId.getText());
        billInfoBLL = new BillInfoBLL();
        billInfoBLL.DeleteBillInfo(billInfoId);
        JOptionPane.showMessageDialog(this, "Xóa món ăn thành công!");
        this.dispose();
        BillDAO billDAO =new BillDAO();
        int billId=billDAO.GetBillId(tableId);
        billInfoBLL.FillBillItem(TableGUI.jTable1,billId);
    }//GEN-LAST:event_btn_DeleteBillItemActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(UpdateBillItemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(UpdateBillItemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(UpdateBillItemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(UpdateBillItemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new UpdateBillItemGUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_DeleteBillItem;
    private javax.swing.JButton btn_UpdateBillItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JSpinner sp_ItemQuantity;
    public static javax.swing.JTextField txtBillInfoId;
    public static javax.swing.JTextArea txt_UpdateNote;
    // End of variables declaration//GEN-END:variables
}
